version: "3.9"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  migrate:
    build: .
    command: python code/manage.py migrate --noinput
    depends_on: 
      - db
  web:
    build: .
    command: python code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    env_file: 
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - migrate

